# Generated by Django 6.0.3 on 2026-03-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='current_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(default='River', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='max_level',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='location',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(default='Safe', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='trend',
            field=models.CharField(default='Stable', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
